import { SITE_URL } from '@/data/emails'

export const CONFIG = {
  MAX_IMAGE_SIZE: 10 * 1024 * 1024, // 10MB
  MAX_PDF_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_IMAGE_TYPES: ['image/png', 'image/jpeg', 'image/webp'],
  ALLOWED_PDF_TYPES: ['application/pdf'],
  FILE_ID_LENGTH: 12,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET || 'files',
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL || SITE_URL,
  MAX_ACTIVE_LINKS_FREE: 5,
  MAX_BUNDLE_FILES_FREE: 5,
  MAX_BUNDLE_FILES_PREMIUM: 20,
  MAX_BUNDLES_FREE: 5,
  MAX_BUNDLES_PREMIUM: 20,
  DRAFT_BUNDLE_TTL_MS: 60 * 60 * 1000,
}
